title: "Adam Lilith" # title
author: "Adam Lilith" # author
description: "Gakko" # description
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Home Chnage, icon: home} # need to be updated
  - {file: "README.md" title: About me, icon: address-card} # need to be updated

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:adamlilith16@gmail.com"} # need to be updated
  - {title: Github, icon: github, url: "https://https://adamlilith16.github.io/"} # need to be updated
  - {title: Twitter, icon: twitter, url: "https:/twitter.com/adamlilith"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
